In [1]:
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

X_train = pd.read_csv("../data/X_train.csv")
X_test = pd.read_csv("../data/X_test.csv")

y_train = pd.read_csv("../data/y_train.csv").squeeze()
y_test = pd.read_csv("../data/y_test.csv").squeeze()

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression(max_iter=1000, random_state=42)

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

In [2]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print(accuracy)

0.84

In [3]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[  1  59]
 [  5 335]]

In [4]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.17      0.02      0.03        60
           1       0.85      0.99      0.91       340

    accuracy                           0.84       400
   macro avg       0.51      0.50      0.47       400
weighted avg       0.75      0.84      0.78       400

In [5]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

y_prob = model.predict_proba(X_test_scaled)[:, 1]

auc = roc_auc_score(y_test, y_prob)

print("AUC:", auc)

AUC: 0.48955882352941177

In [6]:
coef = pd.DataFrame({
    "Feature": X_train.columns,
    "Coefficient": model.coef_[0]
})

coef = coef.sort_values(
    by="Coefficient",
    ascending=False
)

coef.head(10)

               Feature  Coefficient
63    City_Los Angeles     0.390632
40       City_Aberdeen     0.330555
109  Product_plush toy     0.294674
53        City_Glasgow     0.287679
34      State_Scotland     0.173155
72         City_Nagpur     0.163936
70       City_Montreal     0.147652
105   Product_magazine     0.145657
8         SessionMonth     0.134599
5             Quantity     0.132667

In [7]:
wrong = X_test.copy()

wrong["Actual"] = y_test.values

wrong["Prediction"] = y_pred

wrong = wrong[
    wrong["Actual"] != wrong["Prediction"]
]

wrong.head()

,Age,CreditScore,MonthlyIncome,Cost,Price,Quantity,SessionHour,SessionDay,SessionMonth,TotalAmount,...,CampaignSchema _Twitter-ads,Weekday_Friday,Weekday_Monday,Weekday_Saturday,Weekday_Sunday,Weekday_Thursday,Weekday_Tuesday,Weekday_Wednesday,Actual,Prediction
17,40,663,5638,20,35,1,5,7,10,35,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,1
20,33,774,3331,60,100,1,15,23,12,100,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
26,18,730,4842,60,100,6,4,30,5,600,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1
48,58,632,7347,60,90,6,4,19,1,540,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,1
51,71,614,4179,50,80,6,2,5,11,480,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,1